import Navbar from "../components/Navbar";
import "../../globals.css";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className="w-screen overflow-x-hidden bg-gradient-to-t from-[#F1F1F1] to-[#F0991C]">
          <Navbar />
          {children}
        </body>
    </html>
  )
}
